### ISSUE TITLE
Look into PyCharm-specific static type issues related to 1-19, limit scope to mypy.

### ISSUE THREAD

**Issue by philtweir** [flaxandteal/dewret#29]

**Comment by philtweir** [comment]
@elleryames to confirm whether this works in VSCode

**Comment by elleryames** [comment]
Here is an example of what I get using mypy on vs code. 

![Image](https://github.com/flaxandteal/dewret/assets/61203509/d5e55044-bbdc-413c-8e1a-44c91a56292c)

**Comment by elleryames** [comment]
Close. Mypy or options beyond the built in static type checking in PyCharm should be investigated by users using PyCharm. This is not an issue with `dewret`.
