### ISSUE TITLE
[TBC] Documentation tidy-up [1-34,35,36,37,45,48,51]

### ISSUE THREAD

**Issue by philtweir** [flaxandteal/dewret#33]
[id: 1-34], [MINOR]:
git-versionable workflows: while code can be versioned, the changes of a dynamic workflow do
not necessarily clearly correspond to changes in the executed workflow. This maintains a precise
trackable history.
I really don't understand how the pipeline as code concept is related to a git-versioning? The static,
yaml-based workflows are git-versionable as well, aren't they?

[id: 1-35], [EHN], [MINOR]: From my perspective, the docs miss the advantage for the Python workflows by utilizing the power of IDEs for type hints, code navigation, documentation on the fly and last but not the least refactoring and enhanced testing.

[id: 1-36], [EHN], [MODERATE] In general I miss a more basic introduction (for inexperienced users) and motivation for dewret. What are workflows, what are existing approaches and tools to define a
workflow and what makes dewret unique, i.e. why should I use it? Quickstart/Installation

[id: 1-37], [MINOR], [ENH]: As described above, the installation succeed following the given steps. Later on, it would be nice to split the installation instructions into different user groups (pure users and developers, i.e.). I consider the current installation section as instructions for developers. For pure users, it would be nice to refer to the pypi and the conda-package feeds and provide install instructions as
well.

**Comment by elleryames** [comment]
@KamenDimitrov97 : 
- 1-37 is a straightforward enhancement to the docs (how to install from a package feed). 
- 1-36 could also be done, especially a more basic introduction part. You are welcome to take a crack at answering the question "Why should I use `dewret`?". 
- 1-34 is requesting a clarification regarding the first bullet point on the `dewret` home page. Likely a simple re-wording would do here.

**Comment by elleryames** [comment]
I need to clarify the comment 1-35, which is unclear to me.
