### ISSUE TITLE
Revisit CWL output of global variables (feedback 1-21)

### ISSUE THREAD

**Issue by philtweir** [flaxandteal/dewret#8]

**Comment by elleryames** [comment]
Was this addressed in a specific PR, and if so which one?

**Comment by elleryames** [comment]
Given #27 do we need global variables at all (as in being injected inside functions, a-la https://github.com/flaxandteal/dewret/discussions/20 )?

**Comment by elleryames** [comment]
The original issue in which the value of the global variable was not listed in the CWL workflow input parameters has no been fixed in #27. A remaining question is whether the CWL step having two parameters listed despite the corresponding python task only having one, is intended.
